/**
 * Expanded MDCAT Question Bank
 * 30 questions per difficulty × 3 difficulties × 5 subjects = 450 questions
 * Provides a large enough pool for non-repetitive quiz sessions.
 */
import type { Question } from "./quiz-data";

// ═══════════════════════════════════════════
//  BIOLOGY (90 questions: 30 easy, 30 intermediate, 30 hard)
// ═══════════════════════════════════════════

const biologyEasy: Question[] = [
  { id: "be1", subject: "biology", question: "Which organelle is known as the 'powerhouse of the cell'?", options: ["Ribosome", "Nucleus", "Mitochondria", "Endoplasmic Reticulum"], correctAnswer: 2, difficulty: "easy" },
  { id: "be2", subject: "biology", question: "DNA replication occurs during which phase?", options: ["G1 Phase", "S Phase", "G2 Phase", "M Phase"], correctAnswer: 1, difficulty: "easy" },
  { id: "be3", subject: "biology", question: "The process of mRNA formation from DNA is called?", options: ["Translation", "Transcription", "Replication", "Transduction"], correctAnswer: 1, difficulty: "easy" },
  { id: "be4", subject: "biology", question: "Which blood group is known as the universal donor?", options: ["A", "B", "AB", "O"], correctAnswer: 3, difficulty: "easy" },
  { id: "be5", subject: "biology", question: "Which hormone regulates blood sugar levels?", options: ["Thyroxine", "Insulin", "Adrenaline", "Glucagon"], correctAnswer: 1, difficulty: "easy" },
  { id: "be6", subject: "biology", question: "What is the basic unit of life?", options: ["Atom", "Molecule", "Cell", "Tissue"], correctAnswer: 2, difficulty: "easy" },
  { id: "be7", subject: "biology", question: "Photosynthesis occurs in which organelle?", options: ["Mitochondria", "Chloroplast", "Ribosome", "Golgi body"], correctAnswer: 1, difficulty: "easy" },
  { id: "be8", subject: "biology", question: "Which vitamin is produced when skin is exposed to sunlight?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], correctAnswer: 3, difficulty: "easy" },
  { id: "be9", subject: "biology", question: "Red blood cells are produced in the?", options: ["Liver", "Spleen", "Bone marrow", "Kidneys"], correctAnswer: 2, difficulty: "easy" },
  { id: "be10", subject: "biology", question: "Which gas do plants absorb during photosynthesis?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], correctAnswer: 1, difficulty: "easy" },
  { id: "be11", subject: "biology", question: "The largest organ in the human body is?", options: ["Liver", "Brain", "Skin", "Heart"], correctAnswer: 2, difficulty: "easy" },
  { id: "be12", subject: "biology", question: "Which part of the brain controls balance and coordination?", options: ["Cerebrum", "Cerebellum", "Medulla", "Pons"], correctAnswer: 1, difficulty: "easy" },
  { id: "be13", subject: "biology", question: "Hemoglobin contains which metal ion?", options: ["Copper", "Zinc", "Iron", "Magnesium"], correctAnswer: 2, difficulty: "easy" },
  { id: "be14", subject: "biology", question: "How many chambers does the human heart have?", options: ["2", "3", "4", "5"], correctAnswer: 2, difficulty: "easy" },
  { id: "be15", subject: "biology", question: "Which type of muscle is found in the heart?", options: ["Skeletal", "Smooth", "Cardiac", "Voluntary"], correctAnswer: 2, difficulty: "easy" },
  { id: "be16", subject: "biology", question: "The functional unit of the lungs is?", options: ["Nephron", "Neuron", "Alveolus", "Villus"], correctAnswer: 2, difficulty: "easy" },
  { id: "be17", subject: "biology", question: "Which nucleic acid carries genetic information?", options: ["RNA", "DNA", "mRNA", "tRNA"], correctAnswer: 1, difficulty: "easy" },
  { id: "be18", subject: "biology", question: "The human body has how many pairs of chromosomes?", options: ["21", "22", "23", "24"], correctAnswer: 2, difficulty: "easy" },
  { id: "be19", subject: "biology", question: "Which structure protects the brain?", options: ["Ribcage", "Skull", "Vertebral column", "Pelvis"], correctAnswer: 1, difficulty: "easy" },
  { id: "be20", subject: "biology", question: "Bile is produced by which organ?", options: ["Pancreas", "Gallbladder", "Liver", "Stomach"], correctAnswer: 2, difficulty: "easy" },
  { id: "be21", subject: "biology", question: "Which blood cells help in clotting?", options: ["RBCs", "WBCs", "Platelets", "Plasma"], correctAnswer: 2, difficulty: "easy" },
  { id: "be22", subject: "biology", question: "What is the chemical formula of water?", options: ["H₂O₂", "H₂O", "HO", "OH₂"], correctAnswer: 1, difficulty: "easy" },
  { id: "be23", subject: "biology", question: "Diabetes is caused by deficiency of?", options: ["Thyroxine", "Insulin", "Adrenaline", "Growth hormone"], correctAnswer: 1, difficulty: "easy" },
  { id: "be24", subject: "biology", question: "Which system removes waste products from the body?", options: ["Digestive", "Respiratory", "Excretory", "Circulatory"], correctAnswer: 2, difficulty: "easy" },
  { id: "be25", subject: "biology", question: "RNA differs from DNA in having?", options: ["Thymine", "Uracil", "Adenine", "Guanine"], correctAnswer: 1, difficulty: "easy" },
  { id: "be26", subject: "biology", question: "Enzymes are chemically?", options: ["Lipids", "Carbohydrates", "Proteins", "Nucleic acids"], correctAnswer: 2, difficulty: "easy" },
  { id: "be27", subject: "biology", question: "The longest bone in the human body is?", options: ["Humerus", "Tibia", "Femur", "Radius"], correctAnswer: 2, difficulty: "easy" },
  { id: "be28", subject: "biology", question: "Which sense organ detects sound?", options: ["Eye", "Nose", "Ear", "Tongue"], correctAnswer: 2, difficulty: "easy" },
  { id: "be29", subject: "biology", question: "Amoeba reproduces by?", options: ["Budding", "Binary fission", "Fragmentation", "Sporulation"], correctAnswer: 1, difficulty: "easy" },
  { id: "be30", subject: "biology", question: "Normal human body temperature is?", options: ["36°C", "37°C", "38°C", "39°C"], correctAnswer: 1, difficulty: "easy" },
];

const biologyIntermediate: Question[] = [
  { id: "bi1", subject: "biology", question: "Which enzyme unwinds the DNA double helix during replication?", options: ["DNA Polymerase", "Helicase", "Ligase", "Primase"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi2", subject: "biology", question: "Krebs cycle occurs in which part of the cell?", options: ["Cytoplasm", "Nucleus", "Mitochondrial matrix", "Ribosome"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "bi3", subject: "biology", question: "What is the basic structural unit of the kidney?", options: ["Neuron", "Nephron", "Alveoli", "Villi"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi4", subject: "biology", question: "Which type of immunity is provided by vaccination?", options: ["Natural active", "Artificial active", "Natural passive", "Artificial passive"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi5", subject: "biology", question: "The sinoatrial node is also known as?", options: ["AV node", "Pacemaker", "Bundle of His", "Purkinje fibers"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi6", subject: "biology", question: "Which type of RNA carries amino acids to the ribosome?", options: ["mRNA", "tRNA", "rRNA", "snRNA"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi7", subject: "biology", question: "Glycolysis takes place in the?", options: ["Mitochondria", "Nucleus", "Cytoplasm", "Golgi body"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "bi8", subject: "biology", question: "The hormone responsible for fight-or-flight response is?", options: ["Insulin", "Thyroxine", "Adrenaline", "Melatonin"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "bi9", subject: "biology", question: "How many ATP molecules are produced from one glucose in aerobic respiration?", options: ["2", "18", "36-38", "4"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "bi10", subject: "biology", question: "Which structure connects muscle to bone?", options: ["Ligament", "Tendon", "Cartilage", "Fascia"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi11", subject: "biology", question: "Active transport requires?", options: ["Osmosis", "Diffusion", "ATP energy", "No energy"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "bi12", subject: "biology", question: "The function of ribosomes is?", options: ["Energy production", "Protein synthesis", "Lipid synthesis", "Cell division"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi13", subject: "biology", question: "Which phylum do humans belong to?", options: ["Arthropoda", "Chordata", "Mollusca", "Annelida"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi14", subject: "biology", question: "Antibodies are produced by which cells?", options: ["T-cells", "B-cells", "Red blood cells", "Platelets"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi15", subject: "biology", question: "Which part of the flower produces pollen?", options: ["Stigma", "Style", "Anther", "Ovary"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "bi16", subject: "biology", question: "The Bowman's capsule is part of the?", options: ["Heart", "Lung", "Nephron", "Stomach"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "bi17", subject: "biology", question: "Which vitamin deficiency causes scurvy?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "bi18", subject: "biology", question: "Semi-conservative replication was proved by?", options: ["Watson & Crick", "Meselson & Stahl", "Hershey & Chase", "Griffith"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi19", subject: "biology", question: "The largest gland in the human body is?", options: ["Thyroid", "Pancreas", "Liver", "Pituitary"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "bi20", subject: "biology", question: "Oxygen is transported in blood mainly by?", options: ["Plasma", "WBCs", "Hemoglobin", "Platelets"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "bi21", subject: "biology", question: "Which process converts glucose to pyruvate?", options: ["Krebs cycle", "Glycolysis", "Electron transport", "Fermentation"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi22", subject: "biology", question: "The reflex arc involves how many neurons minimum?", options: ["1", "2", "3", "4"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi23", subject: "biology", question: "Which hormone controls the rate of metabolism?", options: ["Insulin", "Thyroxine", "Cortisol", "Glucagon"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi24", subject: "biology", question: "Pepsin works best in which pH?", options: ["pH 2", "pH 7", "pH 9", "pH 12"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "bi25", subject: "biology", question: "Which organelle contains its own DNA?", options: ["Ribosome", "Lysosome", "Mitochondria", "Golgi body"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "bi26", subject: "biology", question: "Transpiration occurs mainly through?", options: ["Roots", "Stomata", "Bark", "Flowers"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi27", subject: "biology", question: "The autonomic nervous system controls?", options: ["Voluntary actions", "Involuntary actions", "Reflexes only", "Thinking"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi28", subject: "biology", question: "Which cell organelle is involved in detoxification?", options: ["Rough ER", "Smooth ER", "Golgi body", "Lysosome"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "bi29", subject: "biology", question: "Incomplete dominance produces?", options: ["Dominant phenotype", "Recessive phenotype", "Blended phenotype", "No phenotype"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "bi30", subject: "biology", question: "Which tissue transports water in plants?", options: ["Phloem", "Xylem", "Parenchyma", "Collenchyma"], correctAnswer: 1, difficulty: "intermediate" },
];

const biologyHard: Question[] = [
  { id: "bh1", subject: "biology", question: "Which nitrogenous base is not found in RNA?", options: ["Adenine", "Thymine", "Uracil", "Cytosine"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh2", subject: "biology", question: "Crossing over occurs during which stage of meiosis?", options: ["Prophase I", "Metaphase I", "Anaphase II", "Telophase II"], correctAnswer: 0, difficulty: "hard" },
  { id: "bh3", subject: "biology", question: "The Hardy-Weinberg equilibrium requires all EXCEPT?", options: ["Large population", "Random mating", "Natural selection", "No mutation"], correctAnswer: 2, difficulty: "hard" },
  { id: "bh4", subject: "biology", question: "Which codon signals the start of translation?", options: ["UAA", "UAG", "AUG", "UGA"], correctAnswer: 2, difficulty: "hard" },
  { id: "bh5", subject: "biology", question: "Restriction enzymes are used in?", options: ["PCR", "Genetic engineering", "Gel electrophoresis", "All of these"], correctAnswer: 3, difficulty: "hard" },
  { id: "bh6", subject: "biology", question: "C4 plants fix CO₂ first into?", options: ["3-PGA", "Oxaloacetate", "RuBP", "G3P"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh7", subject: "biology", question: "Which enzyme adds nucleotides during DNA replication?", options: ["Helicase", "Primase", "DNA Polymerase III", "Ligase"], correctAnswer: 2, difficulty: "hard" },
  { id: "bh8", subject: "biology", question: "The wobble hypothesis explains?", options: ["DNA mutations", "Flexible base pairing at 3rd codon position", "Protein folding", "Gene regulation"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh9", subject: "biology", question: "Operon model was proposed for gene regulation in?", options: ["Eukaryotes", "Prokaryotes", "Viruses", "Fungi"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh10", subject: "biology", question: "Which complex in ETC directly pumps protons?", options: ["Complex I, III, IV", "Complex I, II, III", "Complex II, III, IV", "Complex I, II, IV"], correctAnswer: 0, difficulty: "hard" },
  { id: "bh11", subject: "biology", question: "Polymerase chain reaction (PCR) requires?", options: ["Taq polymerase", "Primers", "dNTPs", "All of these"], correctAnswer: 3, difficulty: "hard" },
  { id: "bh12", subject: "biology", question: "The lac operon is an example of?", options: ["Positive regulation", "Negative regulation", "Both positive and negative", "Neither"], correctAnswer: 2, difficulty: "hard" },
  { id: "bh13", subject: "biology", question: "Cri-du-chat syndrome is caused by?", options: ["Trisomy 21", "Deletion on chromosome 5", "XO genotype", "XXY genotype"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh14", subject: "biology", question: "Which type of selection favors intermediate phenotypes?", options: ["Directional", "Stabilizing", "Disruptive", "Artificial"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh15", subject: "biology", question: "Telomerase is an enzyme that?", options: ["Unwinds DNA", "Adds telomeric repeats", "Repairs mismatches", "Methylates DNA"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh16", subject: "biology", question: "In the Calvin cycle, CO₂ is fixed by which enzyme?", options: ["PEP carboxylase", "RuBisCO", "ATP synthase", "NADP reductase"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh17", subject: "biology", question: "Allopatric speciation requires?", options: ["Behavioral isolation", "Geographic isolation", "Temporal isolation", "Mechanical isolation"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh18", subject: "biology", question: "Which amino acid has the simplest structure?", options: ["Alanine", "Glycine", "Valine", "Leucine"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh19", subject: "biology", question: "Prions are composed of?", options: ["DNA only", "RNA only", "Protein only", "DNA and protein"], correctAnswer: 2, difficulty: "hard" },
  { id: "bh20", subject: "biology", question: "Signal transduction typically involves?", options: ["Receptor, transducer, effector", "Only receptor", "Only effector", "DNA directly"], correctAnswer: 0, difficulty: "hard" },
  { id: "bh21", subject: "biology", question: "The Casparian strip is found in?", options: ["Epidermis", "Endodermis", "Pericycle", "Cortex"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh22", subject: "biology", question: "Which law states that genes on the same chromosome tend to be inherited together?", options: ["Law of segregation", "Law of linkage", "Law of dominance", "Law of independent assortment"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh23", subject: "biology", question: "Reverse transcriptase synthesizes?", options: ["RNA from DNA", "DNA from RNA", "Protein from RNA", "RNA from protein"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh24", subject: "biology", question: "Which structure is absent in prokaryotic cells?", options: ["Ribosome", "Cell membrane", "Membrane-bound nucleus", "DNA"], correctAnswer: 2, difficulty: "hard" },
  { id: "bh25", subject: "biology", question: "Epigenetics involves changes in?", options: ["DNA sequence", "Gene expression without DNA change", "Chromosome number", "Protein structure"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh26", subject: "biology", question: "The P680 and P700 are found in?", options: ["Mitochondria", "Photosystem II and I", "Golgi body", "Nucleus"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh27", subject: "biology", question: "Non-disjunction during meiosis leads to?", options: ["Crossing over", "Aneuploidy", "Polyploidy", "Gene mutation"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh28", subject: "biology", question: "Which type of mutation is a silent mutation?", options: ["Changes amino acid", "Changes nothing in protein", "Adds a stop codon", "Shifts reading frame"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh29", subject: "biology", question: "The oxygen evolving complex is associated with?", options: ["Photosystem I", "Photosystem II", "Cytochrome complex", "ATP synthase"], correctAnswer: 1, difficulty: "hard" },
  { id: "bh30", subject: "biology", question: "CRISPR-Cas9 is used for?", options: ["Gene cloning", "Genome editing", "PCR", "Gel electrophoresis"], correctAnswer: 1, difficulty: "hard" },
];

// ═══════════════════════════════════════════
//  CHEMISTRY (90 questions: 30 easy, 30 intermediate, 30 hard)
// ═══════════════════════════════════════════

const chemistryEasy: Question[] = [
  { id: "ce1", subject: "chemistry", question: "What is the pH of pure water at 25°C?", options: ["5", "7", "8", "14"], correctAnswer: 1, difficulty: "easy" },
  { id: "ce2", subject: "chemistry", question: "Which element has the highest electronegativity?", options: ["Oxygen", "Chlorine", "Fluorine", "Nitrogen"], correctAnswer: 2, difficulty: "easy" },
  { id: "ce3", subject: "chemistry", question: "The shape of methane molecule is?", options: ["Linear", "Trigonal planar", "Tetrahedral", "Octahedral"], correctAnswer: 2, difficulty: "easy" },
  { id: "ce4", subject: "chemistry", question: "Which type of bond is formed in NaCl?", options: ["Covalent", "Ionic", "Metallic", "Hydrogen"], correctAnswer: 1, difficulty: "easy" },
  { id: "ce5", subject: "chemistry", question: "The functional group in aldehydes is?", options: ["-OH", "-COOH", "-CHO", "-CO-"], correctAnswer: 2, difficulty: "easy" },
  { id: "ce6", subject: "chemistry", question: "Which gas is lightest?", options: ["Oxygen", "Nitrogen", "Hydrogen", "Helium"], correctAnswer: 2, difficulty: "easy" },
  { id: "ce7", subject: "chemistry", question: "Atomic number represents the number of?", options: ["Neutrons", "Protons", "Electrons only", "Protons + neutrons"], correctAnswer: 1, difficulty: "easy" },
  { id: "ce8", subject: "chemistry", question: "Which element is a noble gas?", options: ["Nitrogen", "Oxygen", "Neon", "Chlorine"], correctAnswer: 2, difficulty: "easy" },
  { id: "ce9", subject: "chemistry", question: "The chemical formula of table salt is?", options: ["NaCl", "KCl", "CaCl₂", "MgCl₂"], correctAnswer: 0, difficulty: "easy" },
  { id: "ce10", subject: "chemistry", question: "How many electrons can the first shell hold?", options: ["2", "8", "18", "32"], correctAnswer: 0, difficulty: "easy" },
  { id: "ce11", subject: "chemistry", question: "Which acid is found in vinegar?", options: ["HCl", "H₂SO₄", "CH₃COOH", "HNO₃"], correctAnswer: 2, difficulty: "easy" },
  { id: "ce12", subject: "chemistry", question: "Rusting of iron is an example of?", options: ["Physical change", "Chemical change", "Nuclear change", "No change"], correctAnswer: 1, difficulty: "easy" },
  { id: "ce13", subject: "chemistry", question: "Which metal is liquid at room temperature?", options: ["Sodium", "Mercury", "Aluminum", "Iron"], correctAnswer: 1, difficulty: "easy" },
  { id: "ce14", subject: "chemistry", question: "The valency of carbon is?", options: ["2", "3", "4", "5"], correctAnswer: 2, difficulty: "easy" },
  { id: "ce15", subject: "chemistry", question: "Which particle has no charge?", options: ["Proton", "Electron", "Neutron", "Ion"], correctAnswer: 2, difficulty: "easy" },
  { id: "ce16", subject: "chemistry", question: "Baking soda is chemically?", options: ["NaCl", "NaHCO₃", "Na₂CO₃", "NaOH"], correctAnswer: 1, difficulty: "easy" },
  { id: "ce17", subject: "chemistry", question: "Which state of matter has a definite shape?", options: ["Gas", "Liquid", "Solid", "Plasma"], correctAnswer: 2, difficulty: "easy" },
  { id: "ce18", subject: "chemistry", question: "An atom with equal protons and electrons is?", options: ["Cation", "Anion", "Neutral", "Isotope"], correctAnswer: 2, difficulty: "easy" },
  { id: "ce19", subject: "chemistry", question: "Which element is essential for combustion?", options: ["Nitrogen", "Hydrogen", "Oxygen", "Carbon"], correctAnswer: 2, difficulty: "easy" },
  { id: "ce20", subject: "chemistry", question: "Diamond is an allotrope of?", options: ["Silicon", "Carbon", "Sulfur", "Phosphorus"], correctAnswer: 1, difficulty: "easy" },
  { id: "ce21", subject: "chemistry", question: "Acids turn litmus paper?", options: ["Blue", "Red", "Green", "No change"], correctAnswer: 1, difficulty: "easy" },
  { id: "ce22", subject: "chemistry", question: "The formula of sulfuric acid is?", options: ["HCl", "HNO₃", "H₂SO₄", "H₃PO₄"], correctAnswer: 2, difficulty: "easy" },
  { id: "ce23", subject: "chemistry", question: "Which group elements are called halogens?", options: ["Group 1", "Group 2", "Group 17", "Group 18"], correctAnswer: 2, difficulty: "easy" },
  { id: "ce24", subject: "chemistry", question: "Covalent bonds involve?", options: ["Transfer of electrons", "Sharing of electrons", "Loss of protons", "Gain of neutrons"], correctAnswer: 1, difficulty: "easy" },
  { id: "ce25", subject: "chemistry", question: "The molar mass of water (H₂O) is?", options: ["16 g/mol", "18 g/mol", "20 g/mol", "32 g/mol"], correctAnswer: 1, difficulty: "easy" },
  { id: "ce26", subject: "chemistry", question: "Which element has symbol 'K'?", options: ["Krypton", "Potassium", "Calcium", "Cadmium"], correctAnswer: 1, difficulty: "easy" },
  { id: "ce27", subject: "chemistry", question: "Exothermic reactions?", options: ["Absorb heat", "Release heat", "Need catalyst", "Are always slow"], correctAnswer: 1, difficulty: "easy" },
  { id: "ce28", subject: "chemistry", question: "The periodic table is arranged by?", options: ["Atomic mass", "Atomic number", "Number of neutrons", "Alphabetically"], correctAnswer: 1, difficulty: "easy" },
  { id: "ce29", subject: "chemistry", question: "Which solution has pH greater than 7?", options: ["Acidic", "Neutral", "Basic", "None"], correctAnswer: 2, difficulty: "easy" },
  { id: "ce30", subject: "chemistry", question: "Ethanol contains which functional group?", options: ["-CHO", "-COOH", "-OH", "-NH₂"], correctAnswer: 2, difficulty: "easy" },
];

const chemistryIntermediate: Question[] = [
  { id: "ci1", subject: "chemistry", question: "Avogadro's number is approximately?", options: ["6.022 × 10²³", "3.14 × 10²³", "6.022 × 10²²", "1.602 × 10⁻¹⁹"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "ci2", subject: "chemistry", question: "Which gas is produced when zinc reacts with HCl?", options: ["Oxygen", "Hydrogen", "Nitrogen", "Chlorine"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci3", subject: "chemistry", question: "Le Chatelier's principle relates to?", options: ["Thermodynamics", "Chemical equilibrium", "Electrochemistry", "Nuclear chemistry"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci4", subject: "chemistry", question: "The oxidation state of Mn in KMnO₄ is?", options: ["+2", "+4", "+5", "+7"], correctAnswer: 3, difficulty: "intermediate" },
  { id: "ci5", subject: "chemistry", question: "Which law states that equal volumes of gases at same T and P contain equal molecules?", options: ["Boyle's", "Charles's", "Avogadro's", "Dalton's"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ci6", subject: "chemistry", question: "Buffer solution resists change in?", options: ["Temperature", "Volume", "pH", "Pressure"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ci7", subject: "chemistry", question: "The rate of reaction depends on?", options: ["Concentration", "Temperature", "Catalyst", "All of these"], correctAnswer: 3, difficulty: "intermediate" },
  { id: "ci8", subject: "chemistry", question: "sp³ hybridization gives which geometry?", options: ["Linear", "Trigonal planar", "Tetrahedral", "Octahedral"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ci9", subject: "chemistry", question: "Which type of isomerism is shown by CH₃OCH₃ and C₂H₅OH?", options: ["Chain", "Position", "Functional group", "Geometric"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ci10", subject: "chemistry", question: "Molarity is defined as moles of solute per?", options: ["Kg of solvent", "Liter of solution", "Liter of solvent", "Gram of solvent"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci11", subject: "chemistry", question: "In a galvanic cell, oxidation occurs at?", options: ["Cathode", "Anode", "Salt bridge", "Both electrodes"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci12", subject: "chemistry", question: "The ideal gas equation is?", options: ["PV = nRT", "PV = mRT", "PT = nRV", "P = nVRT"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "ci13", subject: "chemistry", question: "Hess's law is based on conservation of?", options: ["Mass", "Energy", "Momentum", "Charge"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci14", subject: "chemistry", question: "Which compound is an alcohol?", options: ["CH₃CHO", "CH₃COOH", "C₂H₅OH", "CH₃OCH₃"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ci15", subject: "chemistry", question: "The VSEPR theory predicts?", options: ["Bond energy", "Molecular shape", "Reaction rate", "Equilibrium"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci16", subject: "chemistry", question: "Enthalpy change at constant pressure equals?", options: ["q_v", "q_p", "w", "ΔG"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci17", subject: "chemistry", question: "Which indicator is used in acid-base titration?", options: ["Starch", "Phenolphthalein", "Methyl red only", "Iodine"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci18", subject: "chemistry", question: "Markovnikov's rule applies to?", options: ["Alkane reactions", "Electrophilic addition to alkenes", "Nucleophilic substitution", "Elimination reactions"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci19", subject: "chemistry", question: "The unit of rate constant for first-order reaction is?", options: ["mol/L·s", "s⁻¹", "L/mol·s", "L²/mol²·s"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci20", subject: "chemistry", question: "Which quantum number describes orbital shape?", options: ["n", "l", "ml", "ms"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci21", subject: "chemistry", question: "Electrolysis of brine produces?", options: ["H₂ and O₂", "NaOH and Cl₂", "HCl and NaOH", "Na and Cl₂"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci22", subject: "chemistry", question: "Which is a Lewis acid?", options: ["NH₃", "BF₃", "H₂O", "OH⁻"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci23", subject: "chemistry", question: "The common ion effect suppresses?", options: ["Solubility", "Boiling point", "Melting point", "Viscosity"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "ci24", subject: "chemistry", question: "Benzene undergoes mainly which type of reactions?", options: ["Addition", "Substitution", "Elimination", "Rearrangement"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci25", subject: "chemistry", question: "Standard temperature and pressure (STP) is?", options: ["0°C, 1 atm", "25°C, 1 atm", "0°C, 2 atm", "100°C, 1 atm"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "ci26", subject: "chemistry", question: "Saponification produces soap and?", options: ["Water", "Glycerol", "Alcohol", "Acid"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci27", subject: "chemistry", question: "Which element shows allotropy: diamond, graphite, fullerene?", options: ["Silicon", "Carbon", "Sulfur", "Phosphorus"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci28", subject: "chemistry", question: "Colligative properties depend on?", options: ["Nature of solute", "Number of solute particles", "Nature of solvent", "Temperature only"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci29", subject: "chemistry", question: "Which reagent is used to test for unsaturation?", options: ["NaOH", "Br₂ water", "HCl", "FeCl₃"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ci30", subject: "chemistry", question: "A catalyst increases reaction rate by?", options: ["Increasing energy", "Lowering activation energy", "Increasing temperature", "Adding reactants"], correctAnswer: 1, difficulty: "intermediate" },
];

const chemistryHard: Question[] = [
  { id: "ch1", subject: "chemistry", question: "The hybridization of carbon in ethylene (C₂H₄) is?", options: ["sp", "sp²", "sp³", "sp³d"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch2", subject: "chemistry", question: "Which quantum number determines the shape of an orbital?", options: ["Principal (n)", "Azimuthal (l)", "Magnetic (ml)", "Spin (ms)"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch3", subject: "chemistry", question: "The Heisenberg uncertainty principle states?", options: ["Energy is quantized", "Position and momentum cannot be simultaneously known", "Electrons have wave nature", "Atoms are indivisible"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch4", subject: "chemistry", question: "Which complex ion is square planar?", options: ["[NiCl₄]²⁻", "[Ni(CN)₄]²⁻", "[CoCl₄]²⁻", "[Fe(H₂O)₆]³⁺"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch5", subject: "chemistry", question: "The Nernst equation relates EMF to?", options: ["Temperature only", "Concentration of reactants/products", "Pressure only", "Volume"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch6", subject: "chemistry", question: "In SN2 mechanism, the rate depends on?", options: ["Substrate only", "Nucleophile only", "Both substrate and nucleophile", "Neither"], correctAnswer: 2, difficulty: "hard" },
  { id: "ch7", subject: "chemistry", question: "Which is the strongest acid among the following?", options: ["HF", "HCl", "HBr", "HI"], correctAnswer: 3, difficulty: "hard" },
  { id: "ch8", subject: "chemistry", question: "Crystal field splitting energy is highest for?", options: ["Octahedral", "Tetrahedral", "Square planar", "Linear"], correctAnswer: 2, difficulty: "hard" },
  { id: "ch9", subject: "chemistry", question: "The Gibbs free energy equation is?", options: ["ΔG = ΔH + TΔS", "ΔG = ΔH - TΔS", "ΔG = ΔH × TΔS", "ΔG = ΔH / TΔS"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch10", subject: "chemistry", question: "Which effect explains the stability of benzene?", options: ["Inductive effect", "Resonance/delocalization", "Hyperconjugation", "Steric effect"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch11", subject: "chemistry", question: "The order of a reaction is determined by?", options: ["Stoichiometry", "Experiment", "Molecularity", "Thermodynamics"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch12", subject: "chemistry", question: "Which compound shows optical isomerism?", options: ["CH₄", "CHCl₃", "CHFClBr", "CCl₄"], correctAnswer: 2, difficulty: "hard" },
  { id: "ch13", subject: "chemistry", question: "Born-Haber cycle is used to calculate?", options: ["Ionization energy", "Lattice energy", "Electron affinity", "Bond energy"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch14", subject: "chemistry", question: "Claisen rearrangement involves migration of?", options: ["Hydrogen", "Alkyl group", "Allyl vinyl ether", "Halogen"], correctAnswer: 2, difficulty: "hard" },
  { id: "ch15", subject: "chemistry", question: "The coordination number in FCC unit cell is?", options: ["4", "6", "8", "12"], correctAnswer: 3, difficulty: "hard" },
  { id: "ch16", subject: "chemistry", question: "Racemic mixture is optically?", options: ["Active dextrorotatory", "Active levorotatory", "Inactive", "Partially active"], correctAnswer: 2, difficulty: "hard" },
  { id: "ch17", subject: "chemistry", question: "Arrhenius equation relates rate constant to?", options: ["Concentration", "Temperature", "Pressure", "Volume"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch18", subject: "chemistry", question: "Which reaction is used in Grignard synthesis?", options: ["RMgX + ketone", "RMgX + alkane", "RLi + ether", "ROH + acid"], correctAnswer: 0, difficulty: "hard" },
  { id: "ch19", subject: "chemistry", question: "The Aufbau principle states that electrons fill?", options: ["Highest energy first", "Lowest energy first", "Randomly", "In pairs only"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch20", subject: "chemistry", question: "Which type of catalysis involves same phase?", options: ["Heterogeneous", "Homogeneous", "Enzyme", "Auto"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch21", subject: "chemistry", question: "The entropy of a perfect crystal at 0 K is?", options: ["Maximum", "Zero", "Infinite", "Undefined"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch22", subject: "chemistry", question: "Aldol condensation requires?", options: ["α-hydrogen", "β-hydrogen", "No hydrogen", "Tertiary carbon"], correctAnswer: 0, difficulty: "hard" },
  { id: "ch23", subject: "chemistry", question: "Lanthanide contraction is due to?", options: ["Poor shielding by 4f electrons", "Nuclear fusion", "Ionic bonding", "Metallic bonding"], correctAnswer: 0, difficulty: "hard" },
  { id: "ch24", subject: "chemistry", question: "Which law relates partial pressures of gases?", options: ["Boyle's law", "Dalton's law", "Henry's law", "Raoult's law"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch25", subject: "chemistry", question: "The half-life of a first-order reaction?", options: ["Depends on concentration", "Is independent of concentration", "Doubles with concentration", "Halves with concentration"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch26", subject: "chemistry", question: "Friedel-Crafts acylation uses which catalyst?", options: ["FeCl₃", "AlCl₃", "ZnCl₂", "CuCl₂"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch27", subject: "chemistry", question: "Spin-only magnetic moment depends on?", options: ["Number of unpaired electrons", "Total electrons", "Atomic mass", "Ionization energy"], correctAnswer: 0, difficulty: "hard" },
  { id: "ch28", subject: "chemistry", question: "Which process converts an aldehyde to a carboxylic acid?", options: ["Reduction", "Oxidation", "Hydrolysis", "Dehydration"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch29", subject: "chemistry", question: "Van der Waals equation accounts for?", options: ["Ideal gas behavior", "Real gas deviations", "Nuclear reactions", "Photochemistry"], correctAnswer: 1, difficulty: "hard" },
  { id: "ch30", subject: "chemistry", question: "Chelation increases complex stability due to?", options: ["Entropy effect", "Enthalpy effect", "Both", "Neither"], correctAnswer: 0, difficulty: "hard" },
];

// ═══════════════════════════════════════════
//  PHYSICS (90 questions: 30 easy, 30 intermediate, 30 hard)
// ═══════════════════════════════════════════

const physicsEasy: Question[] = [
  { id: "pe1", subject: "physics", question: "What is the SI unit of force?", options: ["Joule", "Newton", "Watt", "Pascal"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe2", subject: "physics", question: "The speed of light in vacuum is approximately?", options: ["3 × 10⁶ m/s", "3 × 10⁸ m/s", "3 × 10¹⁰ m/s", "3 × 10⁴ m/s"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe3", subject: "physics", question: "Which law states that F = ma?", options: ["Newton's First", "Newton's Second", "Newton's Third", "Gravitation"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe4", subject: "physics", question: "The unit of electrical resistance is?", options: ["Volt", "Ampere", "Ohm", "Watt"], correctAnswer: 2, difficulty: "easy" },
  { id: "pe5", subject: "physics", question: "What is the SI unit of energy?", options: ["Newton", "Joule", "Watt", "Pascal"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe6", subject: "physics", question: "Which type of mirror is used in car headlights?", options: ["Plane", "Convex", "Concave", "None"], correctAnswer: 2, difficulty: "easy" },
  { id: "pe7", subject: "physics", question: "Acceleration due to gravity on Earth is approximately?", options: ["8.9 m/s²", "9.8 m/s²", "10.8 m/s²", "11.2 m/s²"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe8", subject: "physics", question: "Sound cannot travel through?", options: ["Solids", "Liquids", "Gases", "Vacuum"], correctAnswer: 3, difficulty: "easy" },
  { id: "pe9", subject: "physics", question: "The SI unit of current is?", options: ["Volt", "Ampere", "Ohm", "Coulomb"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe10", subject: "physics", question: "Which color of light has the longest wavelength?", options: ["Blue", "Green", "Yellow", "Red"], correctAnswer: 3, difficulty: "easy" },
  { id: "pe11", subject: "physics", question: "What is the SI unit of power?", options: ["Joule", "Newton", "Watt", "Pascal"], correctAnswer: 2, difficulty: "easy" },
  { id: "pe12", subject: "physics", question: "Velocity is a?", options: ["Scalar quantity", "Vector quantity", "Dimensionless", "Unit"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe13", subject: "physics", question: "Which device converts electrical energy to mechanical?", options: ["Generator", "Motor", "Transformer", "Battery"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe14", subject: "physics", question: "Normal boiling point of water is?", options: ["90°C", "95°C", "100°C", "110°C"], correctAnswer: 2, difficulty: "easy" },
  { id: "pe15", subject: "physics", question: "Echo is due to?", options: ["Refraction", "Reflection of sound", "Diffraction", "Interference"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe16", subject: "physics", question: "The SI unit of frequency is?", options: ["Hertz", "Decibel", "Meter", "Second"], correctAnswer: 0, difficulty: "easy" },
  { id: "pe17", subject: "physics", question: "Which instrument measures atmospheric pressure?", options: ["Thermometer", "Barometer", "Ammeter", "Voltmeter"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe18", subject: "physics", question: "Ohm's law relates voltage to?", options: ["Power and energy", "Current and resistance", "Mass and velocity", "Force and area"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe19", subject: "physics", question: "Which lens is used to correct myopia?", options: ["Convex", "Concave", "Bifocal", "Cylindrical"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe20", subject: "physics", question: "Work done is zero when force is?", options: ["Parallel to displacement", "Perpendicular to displacement", "Equal to displacement", "Double the displacement"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe21", subject: "physics", question: "The SI unit of charge is?", options: ["Ampere", "Volt", "Coulomb", "Ohm"], correctAnswer: 2, difficulty: "easy" },
  { id: "pe22", subject: "physics", question: "Friction always acts in?", options: ["Direction of motion", "Opposite to motion", "Perpendicular to motion", "Any direction"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe23", subject: "physics", question: "Which form of energy does a moving car have?", options: ["Potential", "Kinetic", "Chemical", "Nuclear"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe24", subject: "physics", question: "Density is defined as?", options: ["Mass × Volume", "Mass / Volume", "Volume / Mass", "Mass + Volume"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe25", subject: "physics", question: "Total internal reflection occurs in?", options: ["Vacuum only", "Optical fibers", "Open air", "Metals"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe26", subject: "physics", question: "The center of gravity of a uniform rod is at its?", options: ["End", "Center", "Quarter point", "Random point"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe27", subject: "physics", question: "Specific heat capacity is measured in?", options: ["J/kg", "J/kg·K", "J/K", "W/m·K"], correctAnswer: 1, difficulty: "easy" },
  { id: "pe28", subject: "physics", question: "Which wave does not need a medium?", options: ["Sound wave", "Water wave", "Electromagnetic wave", "Seismic wave"], correctAnswer: 2, difficulty: "easy" },
  { id: "pe29", subject: "physics", question: "1 kilowatt = ?", options: ["100 W", "500 W", "1000 W", "10000 W"], correctAnswer: 2, difficulty: "easy" },
  { id: "pe30", subject: "physics", question: "The image in a plane mirror is?", options: ["Real", "Inverted", "Virtual and laterally inverted", "Magnified"], correctAnswer: 2, difficulty: "easy" },
];

const physicsIntermediate: Question[] = [
  { id: "pi1", subject: "physics", question: "Total internal reflection occurs when light travels from?", options: ["Rarer to denser", "Denser to rarer", "Vacuum to air", "Air to glass"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi2", subject: "physics", question: "The time period of a simple pendulum depends on?", options: ["Mass", "Amplitude", "Length and gravity", "Color"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "pi3", subject: "physics", question: "Which quantity is conserved in elastic collision?", options: ["Only momentum", "Only KE", "Both momentum and KE", "Neither"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "pi4", subject: "physics", question: "Lenz's law is related to?", options: ["Electrostatics", "Electromagnetic induction", "Thermodynamics", "Optics"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi5", subject: "physics", question: "The terminal velocity of a body in a fluid depends on?", options: ["Mass only", "Radius and viscosity", "Color", "Shape only"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi6", subject: "physics", question: "In a transformer, if turns ratio > 1, it is a?", options: ["Step-down", "Step-up", "Isolation", "Auto"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi7", subject: "physics", question: "The escape velocity from Earth is approximately?", options: ["7.9 km/s", "11.2 km/s", "15 km/s", "3 × 10⁵ km/s"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi8", subject: "physics", question: "Kirchhoff's current law is based on conservation of?", options: ["Energy", "Charge", "Mass", "Momentum"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi9", subject: "physics", question: "Young's double slit experiment demonstrates?", options: ["Particle nature", "Wave nature", "Dual nature", "Nuclear nature"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi10", subject: "physics", question: "The moment of inertia depends on?", options: ["Mass distribution and axis", "Velocity", "Acceleration", "Force"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "pi11", subject: "physics", question: "Capacitance of a parallel plate capacitor increases with?", options: ["Increasing distance", "Decreasing area", "Increasing area", "Removing dielectric"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "pi12", subject: "physics", question: "The Doppler effect applies to?", options: ["Only sound", "Only light", "Both sound and light", "Neither"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "pi13", subject: "physics", question: "Bernoulli's equation is based on?", options: ["Conservation of mass", "Conservation of energy", "Newton's laws", "Coulomb's law"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi14", subject: "physics", question: "Which thermodynamic process occurs at constant temperature?", options: ["Adiabatic", "Isothermal", "Isobaric", "Isochoric"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi15", subject: "physics", question: "The resolving power of a microscope increases with?", options: ["Longer wavelength", "Shorter wavelength", "Lower aperture", "Less light"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi16", subject: "physics", question: "Self-inductance is measured in?", options: ["Farad", "Henry", "Ohm", "Weber"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi17", subject: "physics", question: "In SHM, acceleration is maximum at?", options: ["Mean position", "Extreme position", "Midway", "Random point"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi18", subject: "physics", question: "The efficiency of a Carnot engine depends on?", options: ["Working substance", "Temperature of reservoirs", "Volume", "Pressure"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi19", subject: "physics", question: "Eddy currents can be reduced by?", options: ["Using solid core", "Laminating the core", "Increasing current", "Using copper core"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi20", subject: "physics", question: "Which phenomenon proves light is transverse?", options: ["Reflection", "Refraction", "Polarization", "Diffraction"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "pi21", subject: "physics", question: "Angular momentum is conserved when?", options: ["Net force is zero", "Net torque is zero", "Speed is constant", "Mass is constant"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi22", subject: "physics", question: "The energy stored in a capacitor is?", options: ["½CV²", "CV", "CV²", "½C²V"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "pi23", subject: "physics", question: "Wheatstone bridge is used to measure?", options: ["Current", "Voltage", "Resistance", "Capacitance"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "pi24", subject: "physics", question: "Beats are produced due to?", options: ["Reflection", "Superposition of slightly different frequencies", "Refraction", "Diffraction"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi25", subject: "physics", question: "Centripetal acceleration is directed?", options: ["Tangentially", "Toward center", "Away from center", "Along velocity"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi26", subject: "physics", question: "The coefficient of restitution for perfectly elastic collision is?", options: ["0", "0.5", "1", "Infinity"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "pi27", subject: "physics", question: "Faraday's law relates induced EMF to?", options: ["Current change", "Rate of change of flux", "Resistance", "Capacitance"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi28", subject: "physics", question: "Which type of wave is sound?", options: ["Transverse", "Longitudinal", "Electromagnetic", "Standing"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "pi29", subject: "physics", question: "The magnetic field inside a solenoid is?", options: ["Zero", "Non-uniform", "Uniform", "Maximum at ends"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "pi30", subject: "physics", question: "Projectile motion is a combination of?", options: ["Two circular motions", "Horizontal uniform + vertical accelerated", "Two accelerated motions", "Random motions"], correctAnswer: 1, difficulty: "intermediate" },
];

const physicsHard: Question[] = [
  { id: "ph1", subject: "physics", question: "In photoelectric effect, increasing intensity increases?", options: ["Kinetic energy", "Number of electrons", "Frequency", "Wavelength"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph2", subject: "physics", question: "The dimension of Planck's constant is?", options: ["ML²T⁻¹", "ML²T⁻²", "MLT⁻¹", "ML²T⁻³"], correctAnswer: 0, difficulty: "hard" },
  { id: "ph3", subject: "physics", question: "De Broglie wavelength is inversely proportional to?", options: ["Energy", "Momentum", "Frequency", "Mass only"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph4", subject: "physics", question: "In Compton scattering, the shift depends on?", options: ["Wavelength of incident photon", "Angle of scattering", "Intensity", "Material"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph5", subject: "physics", question: "The binding energy per nucleon is maximum for?", options: ["Hydrogen", "Helium", "Iron", "Uranium"], correctAnswer: 2, difficulty: "hard" },
  { id: "ph6", subject: "physics", question: "Maxwell's equations unify?", options: ["Mechanics and optics", "Electricity and magnetism", "Thermodynamics and mechanics", "Quantum and classical"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph7", subject: "physics", question: "Poynting vector represents?", options: ["Electric field", "Magnetic field", "Energy flux of EM wave", "Charge density"], correctAnswer: 2, difficulty: "hard" },
  { id: "ph8", subject: "physics", question: "Which quantum number is not associated with Schrödinger equation?", options: ["n", "l", "ml", "ms"], correctAnswer: 3, difficulty: "hard" },
  { id: "ph9", subject: "physics", question: "Stefan-Boltzmann law states total energy radiated is proportional to?", options: ["T", "T²", "T³", "T⁴"], correctAnswer: 3, difficulty: "hard" },
  { id: "ph10", subject: "physics", question: "In special relativity, mass increases with?", options: ["Decreasing velocity", "Increasing velocity", "Constant velocity", "Zero velocity"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph11", subject: "physics", question: "The Bohr model explains spectrum of?", options: ["All atoms", "Hydrogen-like atoms only", "Multi-electron atoms", "Molecules"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph12", subject: "physics", question: "Lissajous figures are formed by superposition of?", options: ["Longitudinal waves", "Two perpendicular SHMs", "Sound waves", "EM waves"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph13", subject: "physics", question: "The quality factor (Q) of an LCR circuit represents?", options: ["Power loss", "Sharpness of resonance", "Total impedance", "Current gain"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph14", subject: "physics", question: "Zeeman effect is the splitting of spectral lines in?", options: ["Electric field", "Magnetic field", "Gravitational field", "No field"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph15", subject: "physics", question: "The Uncertainty Principle limits simultaneous measurement of?", options: ["Mass and charge", "Position and momentum", "Energy and mass", "Speed and acceleration"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph16", subject: "physics", question: "Pair production requires minimum photon energy of?", options: ["0.511 MeV", "1.022 MeV", "2.044 MeV", "13.6 eV"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph17", subject: "physics", question: "Which force is responsible for beta decay?", options: ["Strong nuclear", "Electromagnetic", "Weak nuclear", "Gravitational"], correctAnswer: 2, difficulty: "hard" },
  { id: "ph18", subject: "physics", question: "Bremsstrahlung radiation is produced when?", options: ["Electrons hit atoms", "Electrons decelerate", "Photons collide", "Nuclei fuse"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph19", subject: "physics", question: "The Hall effect is used to determine?", options: ["Resistance", "Type of charge carriers", "Magnetic field only", "Temperature"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph20", subject: "physics", question: "Rayleigh criterion relates to?", options: ["Diffraction limit of resolution", "Refraction index", "Polarization angle", "Total internal reflection"], correctAnswer: 0, difficulty: "hard" },
  { id: "ph21", subject: "physics", question: "In nuclear fission, mass defect converts to?", options: ["Sound energy", "Kinetic energy", "Binding energy released", "Chemical energy"], correctAnswer: 2, difficulty: "hard" },
  { id: "ph22", subject: "physics", question: "Fermi energy is the highest occupied energy at?", options: ["High temperature", "Absolute zero", "Room temperature", "Boiling point"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph23", subject: "physics", question: "The gyromagnetic ratio relates?", options: ["Charge to mass", "Magnetic moment to angular momentum", "Energy to frequency", "Force to area"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph24", subject: "physics", question: "Brewster's angle is the angle at which reflected light is?", options: ["Fully refracted", "Completely polarized", "Totally reflected", "Absorbed"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph25", subject: "physics", question: "Which semiconductor has a wider band gap?", options: ["Germanium", "Silicon", "Gallium Arsenide", "Tin"], correctAnswer: 2, difficulty: "hard" },
  { id: "ph26", subject: "physics", question: "Meissner effect is associated with?", options: ["Conductors", "Superconductors", "Semiconductors", "Insulators"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph27", subject: "physics", question: "Wien's displacement law relates peak wavelength to?", options: ["Pressure", "Volume", "Temperature", "Density"], correctAnswer: 2, difficulty: "hard" },
  { id: "ph28", subject: "physics", question: "Nuclear fusion requires?", options: ["Low temperature", "Very high temperature", "Room temperature", "Absolute zero"], correctAnswer: 1, difficulty: "hard" },
  { id: "ph29", subject: "physics", question: "The fine structure constant is approximately?", options: ["1/137", "1/100", "1/10", "1/1000"], correctAnswer: 0, difficulty: "hard" },
  { id: "ph30", subject: "physics", question: "Dielectric breakdown occurs when?", options: ["Field is too low", "Electric field exceeds critical value", "Temperature is zero", "No voltage applied"], correctAnswer: 1, difficulty: "hard" },
];

// ═══════════════════════════════════════════
//  ENGLISH GRAMMAR (90 questions: 30 easy, 30 intermediate, 30 hard)
// ═══════════════════════════════════════════

const englishEasy: Question[] = [
  { id: "ee1", subject: "english", question: "Which is a correct sentence?", options: ["He go to school.", "He goes to school.", "He going to school.", "He gone to school."], correctAnswer: 1, difficulty: "easy" },
  { id: "ee2", subject: "english", question: "The past tense of 'write' is?", options: ["Writed", "Written", "Wrote", "Writing"], correctAnswer: 2, difficulty: "easy" },
  { id: "ee3", subject: "english", question: "She is fond ___ music.", options: ["in", "of", "at", "on"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee4", subject: "english", question: "Identify the part of speech of 'quickly': She runs quickly.", options: ["Adjective", "Adverb", "Noun", "Verb"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee5", subject: "english", question: "Choose the correctly spelled word:", options: ["Accomodation", "Accommodation", "Acomodation", "Acommodation"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee6", subject: "english", question: "The plural of 'child' is?", options: ["Childs", "Childrens", "Children", "Childes"], correctAnswer: 2, difficulty: "easy" },
  { id: "ee7", subject: "english", question: "Which is a noun?", options: ["Beautiful", "Quickly", "Happiness", "Run"], correctAnswer: 2, difficulty: "easy" },
  { id: "ee8", subject: "english", question: "Choose the correct article: ___ apple a day keeps the doctor away.", options: ["A", "An", "The", "No article"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee9", subject: "english", question: "What is the superlative of 'good'?", options: ["Gooder", "Goodest", "Best", "Better"], correctAnswer: 2, difficulty: "easy" },
  { id: "ee10", subject: "english", question: "He ___ to school every day.", options: ["go", "goes", "going", "gone"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee11", subject: "english", question: "The opposite of 'hot' is?", options: ["Warm", "Cold", "Cool", "Mild"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee12", subject: "english", question: "'They' is a?", options: ["Noun", "Pronoun", "Verb", "Adjective"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee13", subject: "english", question: "Which sentence is correct?", options: ["She don't like it.", "She doesn't likes it.", "She doesn't like it.", "She not like it."], correctAnswer: 2, difficulty: "easy" },
  { id: "ee14", subject: "english", question: "The past tense of 'go' is?", options: ["Goed", "Gone", "Went", "Going"], correctAnswer: 2, difficulty: "easy" },
  { id: "ee15", subject: "english", question: "Which word is an adjective?", options: ["Slowly", "Beautiful", "Run", "Joy"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee16", subject: "english", question: "I have ___ umbrella.", options: ["a", "an", "the", "no article"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee17", subject: "english", question: "The comparative form of 'tall' is?", options: ["Tallest", "Taller", "More tall", "Most tall"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee18", subject: "english", question: "Which is a conjunction?", options: ["And", "Quickly", "Beautiful", "Under"], correctAnswer: 0, difficulty: "easy" },
  { id: "ee19", subject: "english", question: "'Dogs' is a ___ noun.", options: ["Proper", "Common", "Abstract", "Collective"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee20", subject: "english", question: "She ___ her homework yesterday.", options: ["do", "does", "did", "doing"], correctAnswer: 2, difficulty: "easy" },
  { id: "ee21", subject: "english", question: "The book is ___ the table.", options: ["on", "in", "at", "by"], correctAnswer: 0, difficulty: "easy" },
  { id: "ee22", subject: "english", question: "Which is a verb?", options: ["Table", "Sing", "Beautiful", "Slowly"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee23", subject: "english", question: "The plural of 'mouse' is?", options: ["Mouses", "Mice", "Mouse", "Mousies"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee24", subject: "english", question: "We ___ playing cricket.", options: ["is", "am", "are", "was"], correctAnswer: 2, difficulty: "easy" },
  { id: "ee25", subject: "english", question: "Which sentence has correct punctuation?", options: ["how are you", "How are you?", "how are you.", "How are you"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee26", subject: "english", question: "The antonym of 'happy' is?", options: ["Glad", "Sad", "Joyful", "Cheerful"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee27", subject: "english", question: "I ___ a student.", options: ["is", "am", "are", "be"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee28", subject: "english", question: "Which word is a preposition?", options: ["Run", "Under", "Happy", "Quickly"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee29", subject: "english", question: "The past participle of 'eat' is?", options: ["Ate", "Eaten", "Eating", "Eated"], correctAnswer: 1, difficulty: "easy" },
  { id: "ee30", subject: "english", question: "A sentence must have a?", options: ["Adjective", "Adverb", "Subject and verb", "Preposition"], correctAnswer: 2, difficulty: "easy" },
];

const englishIntermediate: Question[] = [
  { id: "ei1", subject: "english", question: "The synonym of 'Abundant' is?", options: ["Scarce", "Plentiful", "Rare", "Limited"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei2", subject: "english", question: "The antonym of 'Benevolent' is?", options: ["Kind", "Generous", "Malevolent", "Charitable"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ei3", subject: "english", question: "Which sentence is in passive voice?", options: ["She wrote a letter.", "A letter was written by her.", "She is writing.", "She writes letters."], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei4", subject: "english", question: "Choose the correct indirect speech: He said, 'I am happy.'", options: ["He said that he is happy.", "He said that he was happy.", "He said that I am happy.", "He says he was happy."], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei5", subject: "english", question: "If I ___ rich, I would travel the world.", options: ["am", "was", "were", "will be"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ei6", subject: "english", question: "Which is a compound sentence?", options: ["She sang.", "She sang and danced.", "The girl who sang.", "Singing happily."], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei7", subject: "english", question: "The word 'unbelievable' has how many morphemes?", options: ["1", "2", "3", "4"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ei8", subject: "english", question: "Which tense: 'She has been studying for two hours'?", options: ["Present perfect", "Present perfect continuous", "Past perfect", "Past continuous"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei9", subject: "english", question: "'Neither...nor' is a?", options: ["Coordinating conjunction", "Correlative conjunction", "Subordinating conjunction", "Adverb"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei10", subject: "english", question: "Choose the correct sentence:", options: ["Me and him went.", "Him and I went.", "He and I went.", "I and he went."], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ei11", subject: "english", question: "A clause that can stand alone is called?", options: ["Dependent clause", "Independent clause", "Phrase", "Fragment"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei12", subject: "english", question: "The synonym of 'ephemeral' is?", options: ["Eternal", "Short-lived", "Strong", "Beautiful"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei13", subject: "english", question: "Which is a gerund?", options: ["Running is fun.", "She runs.", "Run fast.", "She ran."], correctAnswer: 0, difficulty: "intermediate" },
  { id: "ei14", subject: "english", question: "'Whom' is used as?", options: ["Subject", "Object", "Adjective", "Adverb"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei15", subject: "english", question: "A simile uses which words?", options: ["As and is", "Like or as", "But and or", "Neither and nor"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei16", subject: "english", question: "The antonym of 'verbose' is?", options: ["Wordy", "Concise", "Lengthy", "Detailed"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei17", subject: "english", question: "Which sentence uses the subjunctive mood?", options: ["She is here.", "I wish I were there.", "He goes daily.", "They came."], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei18", subject: "english", question: "An oxymoron is?", options: ["Exaggeration", "Contradictory terms together", "Comparison", "Repetition"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei19", subject: "english", question: "The passive of 'They are building a house' is?", options: ["A house is built.", "A house is being built.", "A house was built.", "A house has been built."], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei20", subject: "english", question: "Which word is an abstract noun?", options: ["Table", "Freedom", "Dog", "River"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei21", subject: "english", question: "'Despite' is followed by?", options: ["A clause", "A noun/gerund", "An adjective", "An adverb"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei22", subject: "english", question: "Identify the figure of speech: 'The world is a stage.'", options: ["Simile", "Metaphor", "Personification", "Hyperbole"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei23", subject: "english", question: "The prefix 'anti-' means?", options: ["Before", "After", "Against", "With"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ei24", subject: "english", question: "A paradox is?", options: ["A true statement", "A contradictory truth", "A comparison", "A question"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei25", subject: "english", question: "Choose correct usage: 'Each of the boys ___ present.'", options: ["are", "were", "was", "have been"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ei26", subject: "english", question: "Which voice: 'The cake was eaten by the children'?", options: ["Active", "Passive", "Imperative", "Interrogative"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei27", subject: "english", question: "A dangling modifier is?", options: ["A correctly placed modifier", "A modifier without a clear subject", "A type of verb", "An adjective clause"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei28", subject: "english", question: "The synonym of 'pragmatic' is?", options: ["Theoretical", "Practical", "Idealistic", "Abstract"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ei29", subject: "english", question: "Which is a complex sentence?", options: ["She sang.", "She sang and danced.", "Although she was tired, she sang.", "Sing!"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ei30", subject: "english", question: "'To let the cat out of the bag' means?", options: ["Release a cat", "Reveal a secret", "Buy a bag", "Hide something"], correctAnswer: 1, difficulty: "intermediate" },
];

const englishHard: Question[] = [
  { id: "eh1", subject: "english", question: "'To burn the midnight oil' means?", options: ["To waste oil", "To work late at night", "To cook at night", "To sleep early"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh2", subject: "english", question: "The plural of 'phenomenon' is?", options: ["Phenomenons", "Phenomena", "Phenomenas", "Phenomeni"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh3", subject: "english", question: "Which is an example of synecdoche?", options: ["The pen is mightier than the sword.", "Time flies.", "All hands on deck.", "She has a heart of gold."], correctAnswer: 2, difficulty: "hard" },
  { id: "eh4", subject: "english", question: "An appositive is?", options: ["A verb phrase", "A renaming noun phrase", "An adverb clause", "A conjunction"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh5", subject: "english", question: "The word 'antidisestablishmentarianism' has how many syllables?", options: ["10", "11", "12", "13"], correctAnswer: 2, difficulty: "hard" },
  { id: "eh6", subject: "english", question: "Which sentence uses correct parallel structure?", options: ["She likes reading, writing, and to swim.", "She likes reading, writing, and swimming.", "She likes to read, writing, and swim.", "She read, writes, and swimming."], correctAnswer: 1, difficulty: "hard" },
  { id: "eh7", subject: "english", question: "A zeugma is?", options: ["Using one word with two meanings simultaneously", "Repeating a word", "Asking a question", "Comparing two things"], correctAnswer: 0, difficulty: "hard" },
  { id: "eh8", subject: "english", question: "The subjunctive mood is used for?", options: ["Facts", "Hypothetical situations", "Commands only", "Questions only"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh9", subject: "english", question: "'Litotes' is an understatement using?", options: ["Exaggeration", "Double negative", "Comparison", "Repetition"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh10", subject: "english", question: "The plural of 'criterion' is?", options: ["Criterions", "Criteria", "Criterias", "Criterii"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh11", subject: "english", question: "An anacoluthon is?", options: ["A broken sentence structure", "A type of rhyme", "A comparison", "A vowel sound"], correctAnswer: 0, difficulty: "hard" },
  { id: "eh12", subject: "english", question: "'Metonymy' differs from 'synecdoche' in that it uses?", options: ["Part for whole", "Whole for part", "Associated concept", "Opposite meaning"], correctAnswer: 2, difficulty: "hard" },
  { id: "eh13", subject: "english", question: "The word 'inflammable' means?", options: ["Not flammable", "Easily set on fire", "Fireproof", "Slow burning"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh14", subject: "english", question: "A syllepsis involves one word governing two in different senses, similar to?", options: ["Metaphor", "Zeugma", "Simile", "Irony"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh15", subject: "english", question: "Which is correct: 'Who/Whom did you see?'", options: ["Who did you see?", "Whom did you see?", "Both are correct.", "Neither is correct."], correctAnswer: 1, difficulty: "hard" },
  { id: "eh16", subject: "english", question: "An epistrophe is repetition at the?", options: ["Beginning of clauses", "End of clauses", "Middle of sentences", "Between paragraphs"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh17", subject: "english", question: "The word 'enormity' primarily means?", options: ["Huge size", "Great wickedness", "Importance", "Complexity"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh18", subject: "english", question: "Which mood expresses a command?", options: ["Indicative", "Subjunctive", "Imperative", "Conditional"], correctAnswer: 2, difficulty: "hard" },
  { id: "eh19", subject: "english", question: "'Chiasmus' involves?", options: ["Reversed parallel structure", "Simple repetition", "Sound imitation", "Understatement"], correctAnswer: 0, difficulty: "hard" },
  { id: "eh20", subject: "english", question: "The difference between 'affect' and 'effect' is?", options: ["No difference", "Affect=verb, Effect=noun usually", "Affect=noun, Effect=verb", "They are synonyms"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh21", subject: "english", question: "A pleonasm is?", options: ["Using fewer words", "Using redundant words", "Using foreign words", "Using archaic words"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh22", subject: "english", question: "'Tmesis' is inserting a word into?", options: ["A sentence", "The middle of another word", "A paragraph", "A clause"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh23", subject: "english", question: "The plural of 'syllabus' is?", options: ["Syllabuses", "Syllabi", "Both A and B", "Syllabae"], correctAnswer: 2, difficulty: "hard" },
  { id: "eh24", subject: "english", question: "'Anadiplosis' repeats the ___ of one clause at the ___ of the next.", options: ["End, beginning", "Beginning, end", "Middle, middle", "End, end"], correctAnswer: 0, difficulty: "hard" },
  { id: "eh25", subject: "english", question: "Which is correct: 'Fewer' or 'Less' items?", options: ["Fewer for countable", "Less for countable", "Both interchangeable", "Neither is correct"], correctAnswer: 0, difficulty: "hard" },
  { id: "eh26", subject: "english", question: "A 'malapropism' is?", options: ["Correct word usage", "Humorous misuse of a similar-sounding word", "A type of rhyme", "A grammatical rule"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh27", subject: "english", question: "The difference between 'imply' and 'infer' is?", options: ["No difference", "Speaker implies, listener infers", "Speaker infers, listener implies", "They are antonyms"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh28", subject: "english", question: "'Anaphora' is repetition at the?", options: ["End of successive clauses", "Beginning of successive clauses", "Random positions", "Middle of sentences"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh29", subject: "english", question: "A 'portmanteau' word is?", options: ["An archaic word", "A blend of two words", "A borrowed word", "A compound word"], correctAnswer: 1, difficulty: "hard" },
  { id: "eh30", subject: "english", question: "The subjunctive 'were' in 'If I were you' is called?", options: ["Past subjunctive", "Present subjunctive", "Future subjunctive", "Perfect subjunctive"], correctAnswer: 0, difficulty: "hard" },
];

// ═══════════════════════════════════════════
//  LOGICAL REASONING (90 questions: 30 easy, 30 intermediate, 30 hard)
// ═══════════════════════════════════════════

const reasoningEasy: Question[] = [
  { id: "re1", subject: "reasoning", question: "If A = 1, B = 2, C = 3, then CAB = ?", options: ["312", "321", "123", "213"], correctAnswer: 0, difficulty: "easy" },
  { id: "re2", subject: "reasoning", question: "Which number comes next: 1, 1, 2, 3, 5, 8, ?", options: ["10", "11", "12", "13"], correctAnswer: 3, difficulty: "easy" },
  { id: "re3", subject: "reasoning", question: "Find the odd one out: Dog, Cat, Cow, Rose", options: ["Dog", "Cat", "Cow", "Rose"], correctAnswer: 3, difficulty: "easy" },
  { id: "re4", subject: "reasoning", question: "If Monday = 1, then Friday = ?", options: ["4", "5", "6", "7"], correctAnswer: 1, difficulty: "easy" },
  { id: "re5", subject: "reasoning", question: "What is the next letter: A, C, E, G, ?", options: ["H", "I", "J", "K"], correctAnswer: 1, difficulty: "easy" },
  { id: "re6", subject: "reasoning", question: "5 + 3 × 2 = ?", options: ["16", "11", "13", "10"], correctAnswer: 1, difficulty: "easy" },
  { id: "re7", subject: "reasoning", question: "Which shape has 4 equal sides?", options: ["Rectangle", "Triangle", "Square", "Pentagon"], correctAnswer: 2, difficulty: "easy" },
  { id: "re8", subject: "reasoning", question: "Odd one out: 2, 4, 7, 8, 10", options: ["2", "4", "7", "8"], correctAnswer: 2, difficulty: "easy" },
  { id: "re9", subject: "reasoning", question: "If all roses are flowers, and some flowers are red, then?", options: ["All roses are red", "Some roses may be red", "No roses are red", "All flowers are roses"], correctAnswer: 1, difficulty: "easy" },
  { id: "re10", subject: "reasoning", question: "Complete: 10, 20, 30, 40, ?", options: ["45", "50", "55", "60"], correctAnswer: 1, difficulty: "easy" },
  { id: "re11", subject: "reasoning", question: "Which is the smallest: 0.5, 0.05, 0.55, 0.005?", options: ["0.5", "0.05", "0.55", "0.005"], correctAnswer: 3, difficulty: "easy" },
  { id: "re12", subject: "reasoning", question: "How many months have 31 days?", options: ["5", "6", "7", "8"], correctAnswer: 2, difficulty: "easy" },
  { id: "re13", subject: "reasoning", question: "If pen is to write, then knife is to?", options: ["Sharp", "Cut", "Steel", "Kitchen"], correctAnswer: 1, difficulty: "easy" },
  { id: "re14", subject: "reasoning", question: "Which day comes after Wednesday?", options: ["Monday", "Tuesday", "Thursday", "Friday"], correctAnswer: 2, difficulty: "easy" },
  { id: "re15", subject: "reasoning", question: "12 is 25% of?", options: ["36", "48", "60", "3"], correctAnswer: 1, difficulty: "easy" },
  { id: "re16", subject: "reasoning", question: "Odd one out: Apple, Mango, Carrot, Banana", options: ["Apple", "Mango", "Carrot", "Banana"], correctAnswer: 2, difficulty: "easy" },
  { id: "re17", subject: "reasoning", question: "If ABCD = 1234, then DCBA = ?", options: ["4321", "1234", "3214", "2143"], correctAnswer: 0, difficulty: "easy" },
  { id: "re18", subject: "reasoning", question: "A square has how many lines of symmetry?", options: ["2", "3", "4", "6"], correctAnswer: 2, difficulty: "easy" },
  { id: "re19", subject: "reasoning", question: "Next in series: 3, 6, 9, 12, ?", options: ["14", "15", "16", "18"], correctAnswer: 1, difficulty: "easy" },
  { id: "re20", subject: "reasoning", question: "If today is Sunday, what day was yesterday?", options: ["Friday", "Saturday", "Monday", "Thursday"], correctAnswer: 1, difficulty: "easy" },
  { id: "re21", subject: "reasoning", question: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], correctAnswer: 1, difficulty: "easy" },
  { id: "re22", subject: "reasoning", question: "Bird is to fly as fish is to?", options: ["Walk", "Swim", "Run", "Crawl"], correctAnswer: 1, difficulty: "easy" },
  { id: "re23", subject: "reasoning", question: "What is half of 64?", options: ["30", "32", "34", "36"], correctAnswer: 1, difficulty: "easy" },
  { id: "re24", subject: "reasoning", question: "Which number is prime: 4, 6, 7, 9?", options: ["4", "6", "7", "9"], correctAnswer: 2, difficulty: "easy" },
  { id: "re25", subject: "reasoning", question: "Complete the analogy: Hot:Cold :: Day:?", options: ["Sun", "Night", "Light", "Morning"], correctAnswer: 1, difficulty: "easy" },
  { id: "re26", subject: "reasoning", question: "If you rearrange 'LISTEN', you get?", options: ["TINSEL", "SILENT", "ENLIST", "All of these"], correctAnswer: 3, difficulty: "easy" },
  { id: "re27", subject: "reasoning", question: "How many vowels in 'EDUCATION'?", options: ["3", "4", "5", "6"], correctAnswer: 2, difficulty: "easy" },
  { id: "re28", subject: "reasoning", question: "In a race, if you pass the 2nd person, you are in ___ place.", options: ["1st", "2nd", "3rd", "4th"], correctAnswer: 1, difficulty: "easy" },
  { id: "re29", subject: "reasoning", question: "What is 15% of 200?", options: ["20", "25", "30", "35"], correctAnswer: 2, difficulty: "easy" },
  { id: "re30", subject: "reasoning", question: "Odd one out: Circle, Square, Triangle, Cube", options: ["Circle", "Square", "Triangle", "Cube"], correctAnswer: 3, difficulty: "easy" },
];

const reasoningIntermediate: Question[] = [
  { id: "ri1", subject: "reasoning", question: "Complete the series: 2, 6, 12, 20, ?", options: ["28", "30", "32", "24"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ri2", subject: "reasoning", question: "A is B's brother. C is B's mother. D is C's father. How is A related to D?", options: ["Grandfather", "Grandson", "Son", "Father"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ri3", subject: "reasoning", question: "Mirror image of 'AMBULANCE' appears as?", options: ["ECNALUBMA", "AMBULANCE reversed", "ECNALUBMA", "None"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "ri4", subject: "reasoning", question: "If 64 = 8², then √144 = ?", options: ["10", "11", "12", "14"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ri5", subject: "reasoning", question: "In a certain code, COMPUTER = DPNQVUFS. What is DATA?", options: ["EBUB", "DCUC", "EBUB", "CZSY"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "ri6", subject: "reasoning", question: "Complete: 1, 4, 9, 16, 25, ?", options: ["30", "35", "36", "49"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ri7", subject: "reasoning", question: "Pointing to a photo, A says 'She is my mother's only daughter's daughter.' Who is she?", options: ["A's sister", "A's daughter", "A's niece", "A's mother"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ri8", subject: "reasoning", question: "If South-East becomes North, then North-East becomes?", options: ["South", "West", "South-West", "North-West"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ri9", subject: "reasoning", question: "Which number replaces ?: 3, 5, 9, 17, ?", options: ["25", "31", "33", "35"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ri10", subject: "reasoning", question: "A clock shows 3:15. What is the angle between hands?", options: ["0°", "7.5°", "15°", "22.5°"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ri11", subject: "reasoning", question: "How many triangles in a pentagram (5-pointed star)?", options: ["5", "10", "15", "20"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ri12", subject: "reasoning", question: "If 'FRIEND' = 54, what is 'ENEMY' = ?", options: ["45", "50", "55", "63"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ri13", subject: "reasoning", question: "A man walks 5 km N, then 3 km E. His distance from start?", options: ["√34 km", "8 km", "√28 km", "4 km"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "ri14", subject: "reasoning", question: "Statement: All cats are animals. All animals breathe. Conclusion?", options: ["All cats breathe", "Some cats don't breathe", "No conclusion", "Animals are cats"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "ri15", subject: "reasoning", question: "Next in series: J, F, M, A, M, ?", options: ["J", "A", "S", "O"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "ri16", subject: "reasoning", question: "If × means +, + means −, − means ×, then 5 × 3 + 2 − 4 = ?", options: ["16", "12", "6", "14"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "ri17", subject: "reasoning", question: "Find the missing number: 2, 3, 5, 7, 11, 13, ?", options: ["15", "17", "19", "21"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ri18", subject: "reasoning", question: "In how many ways can 3 books be arranged on a shelf?", options: ["3", "6", "9", "12"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ri19", subject: "reasoning", question: "A is taller than B, B is taller than C. Who is shortest?", options: ["A", "B", "C", "Cannot determine"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ri20", subject: "reasoning", question: "If PALE is coded 2134, what is LEAP?", options: ["4312", "4321", "3412", "1234"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "ri21", subject: "reasoning", question: "A train 100 m long passes a pole in 10 seconds. Its speed is?", options: ["10 m/s", "36 km/h", "Both A and B", "20 m/s"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ri22", subject: "reasoning", question: "Which Venn diagram represents: Dogs, Animals, Cats?", options: ["Two separate circles in one large", "Three overlapping", "Dogs inside Animals, Cats inside Animals", "All identical"], correctAnswer: 2, difficulty: "intermediate" },
  { id: "ri23", subject: "reasoning", question: "Complete: 100, 95, 85, 70, ?", options: ["50", "55", "45", "60"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "ri24", subject: "reasoning", question: "How many squares on a standard chessboard?", options: ["64", "204", "256", "100"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ri25", subject: "reasoning", question: "If the day before yesterday was Thursday, what day is tomorrow?", options: ["Saturday", "Sunday", "Monday", "Friday"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ri26", subject: "reasoning", question: "Find the pattern: ACE, BDF, CEG, ?", options: ["DFH", "DEF", "EFG", "DGI"], correctAnswer: 0, difficulty: "intermediate" },
  { id: "ri27", subject: "reasoning", question: "A is twice as old as B was 5 years ago. B is 15. How old is A?", options: ["15", "20", "25", "30"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ri28", subject: "reasoning", question: "Which figure completes the pattern: ○△□, △□○, □○?", options: ["○", "△", "□", "◇"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ri29", subject: "reasoning", question: "Probability of getting heads in one coin toss?", options: ["0.25", "0.5", "0.75", "1"], correctAnswer: 1, difficulty: "intermediate" },
  { id: "ri30", subject: "reasoning", question: "If all bloops are razzles and all razzles are lazzles, then?", options: ["All lazzles are bloops", "All bloops are lazzles", "Some lazzles are bloops", "Both B and C"], correctAnswer: 3, difficulty: "intermediate" },
];

const reasoningHard: Question[] = [
  { id: "rh1", subject: "reasoning", question: "If APPLE is coded as 50, what is MANGO coded as?", options: ["52", "55", "57", "60"], correctAnswer: 0, difficulty: "hard" },
  { id: "rh2", subject: "reasoning", question: "If 3×4 = 15, 5×6 = 33, then 7×8 = ?", options: ["55", "57", "59", "63"], correctAnswer: 2, difficulty: "hard" },
  { id: "rh3", subject: "reasoning", question: "A die is thrown twice. Probability of sum = 7?", options: ["1/6", "1/12", "1/36", "5/36"], correctAnswer: 0, difficulty: "hard" },
  { id: "rh4", subject: "reasoning", question: "In a group of 100, 70 like tea, 80 like coffee. Minimum who like both?", options: ["30", "40", "50", "60"], correctAnswer: 2, difficulty: "hard" },
  { id: "rh5", subject: "reasoning", question: "Statement: Some dogs are cats. No cats are birds. Conclusion?", options: ["Some dogs are not birds", "All dogs are birds", "No conclusion", "All birds are dogs"], correctAnswer: 0, difficulty: "hard" },
  { id: "rh6", subject: "reasoning", question: "If 1=5, 2=25, 3=125, then 4=?", options: ["500", "625", "1000", "525"], correctAnswer: 1, difficulty: "hard" },
  { id: "rh7", subject: "reasoning", question: "A cube is painted red on all faces, cut into 27 equal cubes. How many have exactly 2 painted faces?", options: ["6", "8", "12", "1"], correctAnswer: 2, difficulty: "hard" },
  { id: "rh8", subject: "reasoning", question: "Next: 1, 2, 6, 24, 120, ?", options: ["240", "480", "720", "600"], correctAnswer: 2, difficulty: "hard" },
  { id: "rh9", subject: "reasoning", question: "In how many ways can 5 people sit in a circle?", options: ["24", "120", "60", "12"], correctAnswer: 0, difficulty: "hard" },
  { id: "rh10", subject: "reasoning", question: "A says: 'B always lies.' B says: 'A always lies.' If one always lies and one always tells truth, who tells truth?", options: ["A", "B", "Both", "Cannot determine with given info"], correctAnswer: 3, difficulty: "hard" },
  { id: "rh11", subject: "reasoning", question: "If log₂(x) = 5, then x = ?", options: ["10", "25", "32", "64"], correctAnswer: 2, difficulty: "hard" },
  { id: "rh12", subject: "reasoning", question: "Three switches control three bulbs in another room. Min visits to identify all?", options: ["1", "2", "3", "It's impossible"], correctAnswer: 0, difficulty: "hard" },
  { id: "rh13", subject: "reasoning", question: "In a knockout tournament with 64 players, total matches needed?", options: ["32", "63", "64", "128"], correctAnswer: 1, difficulty: "hard" },
  { id: "rh14", subject: "reasoning", question: "If you have 3 red and 5 blue socks in the dark, min socks for a matching pair?", options: ["2", "3", "4", "5"], correctAnswer: 1, difficulty: "hard" },
  { id: "rh15", subject: "reasoning", question: "Sum of angles in a polygon with n sides is?", options: ["180n", "(n-2)×180", "360", "n×360"], correctAnswer: 1, difficulty: "hard" },
  { id: "rh16", subject: "reasoning", question: "A palindrome reads same forwards and backwards. Which is NOT a palindrome?", options: ["RADAR", "LEVEL", "ROTOR", "MOTOR"], correctAnswer: 3, difficulty: "hard" },
  { id: "rh17", subject: "reasoning", question: "How many digits in 2¹⁰?", options: ["3", "4", "5", "2"], correctAnswer: 1, difficulty: "hard" },
  { id: "rh18", subject: "reasoning", question: "In base 2, what is 1010 + 1011?", options: ["10101", "10110", "10001", "10100"], correctAnswer: 0, difficulty: "hard" },
  { id: "rh19", subject: "reasoning", question: "A truth table with 3 variables has how many rows?", options: ["4", "6", "8", "16"], correctAnswer: 2, difficulty: "hard" },
  { id: "rh20", subject: "reasoning", question: "If P→Q is true and Q is false, then P is?", options: ["True", "False", "Unknown", "Both true and false"], correctAnswer: 1, difficulty: "hard" },
  { id: "rh21", subject: "reasoning", question: "The contrapositive of 'If it rains, the ground is wet' is?", options: ["If ground is wet, it rains", "If it doesn't rain, ground is not wet", "If ground is not wet, it didn't rain", "None"], correctAnswer: 2, difficulty: "hard" },
  { id: "rh22", subject: "reasoning", question: "How many handshakes among 10 people if each shakes with every other?", options: ["45", "90", "100", "50"], correctAnswer: 0, difficulty: "hard" },
  { id: "rh23", subject: "reasoning", question: "If a clock gains 5 minutes every hour, what time does it show after 12 real hours (starting at 12:00)?", options: ["12:00", "12:60", "1:00", "1:00 (next hour)"], correctAnswer: 2, difficulty: "hard" },
  { id: "rh24", subject: "reasoning", question: "Deductive reasoning goes from?", options: ["Specific to general", "General to specific", "Observation to theory", "Example to example"], correctAnswer: 1, difficulty: "hard" },
  { id: "rh25", subject: "reasoning", question: "How many 3-digit numbers can be formed using 1,2,3 without repetition?", options: ["3", "6", "9", "27"], correctAnswer: 1, difficulty: "hard" },
  { id: "rh26", subject: "reasoning", question: "The Monty Hall problem: should you switch doors?", options: ["Yes, probability increases to 2/3", "No, it stays 1/2", "Doesn't matter", "Probability decreases"], correctAnswer: 0, difficulty: "hard" },
  { id: "rh27", subject: "reasoning", question: "If every A is B, and every B is C, and some C are D, then?", options: ["All A are D", "Some A may be D", "No A are D", "All D are A"], correctAnswer: 1, difficulty: "hard" },
  { id: "rh28", subject: "reasoning", question: "In a leap year, February has how many days?", options: ["28", "29", "30", "31"], correctAnswer: 1, difficulty: "hard" },
  { id: "rh29", subject: "reasoning", question: "The pigeonhole principle states that if n+1 items go into n boxes?", options: ["One box has at least 2", "All boxes are equal", "One box is empty", "Cannot determine"], correctAnswer: 0, difficulty: "hard" },
  { id: "rh30", subject: "reasoning", question: "A recursive sequence: a₁=1, aₙ=2aₙ₋₁+1. What is a₄?", options: ["7", "9", "15", "31"], correctAnswer: 2, difficulty: "hard" },
];

// ═══════════════════════════════════════════
//  EXPORT COMBINED BANK
// ═══════════════════════════════════════════

export const questionBank: Question[] = [
  ...biologyEasy, ...biologyIntermediate, ...biologyHard,
  ...chemistryEasy, ...chemistryIntermediate, ...chemistryHard,
  ...physicsEasy, ...physicsIntermediate, ...physicsHard,
  ...englishEasy, ...englishIntermediate, ...englishHard,
  ...reasoningEasy, ...reasoningIntermediate, ...reasoningHard,
];
